import type { AnalysisResponse } from "./analysisSchema";

export const demoAnalysis: AnalysisResponse = {
  bundleType: "Фьючерс + Фьючерс",
  legs: [
    {
      id: "demo-long-future",
      label: "Long INUSDT",
      type: "futures",
      symbol: "INUSDT",
      side: "long",
      startedAt: "09.07.2026 11:20",
      endedAt: "09.07.2026 12:05",
      volumeUsdt: 1017.65,
      pnlUsdt: -303.64,
      realizedPnlUsdt: -303.64,
      rawPnlUsdt: null,
      roiPercent: null,
      method: "unknown",
      balanceBeforeUsdt: null,
      balanceAfterUsdt: null,
      revenueUsdt: null,
      costUsdt: null,
    },
    {
      id: "demo-short-future",
      label: "Short INUSDT",
      type: "futures",
      symbol: "INUSDT",
      side: "short",
      startedAt: "09.07.2026 11:22",
      endedAt: "09.07.2026 12:07",
      volumeUsdt: 1032.98,
      pnlUsdt: 319.44,
      realizedPnlUsdt: 319.44,
      rawPnlUsdt: null,
      roiPercent: null,
      method: "unknown",
      balanceBeforeUsdt: null,
      balanceAfterUsdt: null,
      revenueUsdt: null,
      costUsdt: null,
    },
  ],
  future: {
    symbol: "INUSDT",
    side: "long",
    startedAt: "09.07.2026 11:20",
    endedAt: "09.07.2026 12:07",
    volumeUsdt: 1017.65,
    roiPercent: null,
    realizedPnlUsdt: -303.64,
  },
  spot: {
    method: "unknown",
    volumeUsdt: null,
    rawPnlUsdt: null,
    pnlUsdt: null,
    balanceBeforeUsdt: null,
    balanceAfterUsdt: null,
    revenueUsdt: null,
    costUsdt: null,
  },
  conflicts: [],
  confidence: 1,
  notes: [],
};
